"""update tabel hotel untuk simpan link gambar

Revision ID: 10d0e098cd20
Revises: faf1a096c511
Create Date: 2024-12-17 18:51:53.676786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10d0e098cd20'
down_revision = 'faf1a096c511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
