"""tambah kolom hotel url pada tabel hotel

Revision ID: 8d0681b98101
Revises: 10d0e098cd20
Create Date: 2024-12-21 13:14:46.589973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d0681b98101'
down_revision = '10d0e098cd20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hotel_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.drop_column('hotel_url')

    # ### end Alembic commands ###
