"""buat hapus cascade

Revision ID: aa568501a39a
Revises: af6649aab16a
Create Date: 2024-12-01 15:09:04.716979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa568501a39a'
down_revision = 'af6649aab16a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.drop_constraint('hotels_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tourist_area_hotel', ['turiareahotel_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('hotels_ibfk_1', 'tourist_area_hotel', ['turiareahotel_id'], ['id'])

    # ### end Alembic commands ###
