"""Menambahkan kolom image_url dengan tipe TEXT ke TouristAreaHotel

Revision ID: faf1a096c511
Revises: bb8653d5c0ef
Create Date: 2024-12-16 21:57:27.578002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faf1a096c511'
down_revision = 'bb8653d5c0ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tourist_area_hotel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tourist_area_hotel', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
